### ISSUE TITLE
Uygulamaları favorilere eklemek

### ISSUE THREAD

**Issue by enderahmetyurt** [calismamasam/calismamasam.com#12]
Röportajlarda geçen insanların kullandıkları uygulamaları favorilere ekleyerek, sonrasında dönüp bakmamıza yardımcı olabilir.

**Comment by tgezginis** [comment]
Evet güzel bir özellik olabilir. Vakit bulunca bakmaya çalışacağım.

**Comment by tgezginis** [comment]
@roguearch eline sağlık. Geliştirmeyi merge ettim, birkaç arayüz güncellemesi yapıp yayına alacağım. 👍

**Comment by tgezginis** [comment]
Geliştirmeler yayında, teşekkürler @roguearch
