### ISSUE TITLE
Kullanıcının daha önce yaptığı röportajın gösterimi

### ISSUE THREAD

**Issue by enderahmetyurt** [calismamasam/calismamasam.com#14]
Calısmasam.com'a kayıt olmuş birinin röportajı varsa belki röportajım altında görülebilir kendi sayfasında. Böylelikle eskileri yad edebilir :)

**Comment by tgezginis** [comment]
Sadece bu özellik için pek gerekli gelmedi bana, ama bir public bir profil sayfası yaratıp orada diğer mecralarda da yaptığı röportaj vb. içerikleri ekletebiliriz.

**Comment by enderahmetyurt** [comment]
Evet yazarken ben bile ne gerek var oldum ama beyin fırtınası olması açısından iyi oldu :)

**Comment by tgezginis** [comment]
Aynen buradan public profil sayfasına evrilebilir. :)
