### ISSUE TITLE
API

### ISSUE THREAD

**Issue by enderahmetyurt** [calismamasam/calismamasam.com#2]
Merhaba @tgezginis API yapmayı düşündün mü? Başka platformlara açılmak iyi olabilir belki.

**Comment by tgezginis** [comment]
Güzel olabilir fakat şu ana kadar herhangi bir kullanım alanı-isteği olmadı. Bu şekilde bir talep gelirse değerlendirilebilir. 👍

**Comment by enderahmetyurt** [comment]
Tamam ben istek yapıyorum o halde. Mobil bir uygulama yazalım native :)

**Comment by tgezginis** [comment]
Mobil uygulama ile ilgili herhangi bir çalışma başlarsa API geliştirmelerine hemen başlarız 👍

**Comment by enderahmetyurt** [comment]
API olsun da başlasın işte 💯
