### ISSUE TITLE
Google AMP geliştirmesi

### ISSUE THREAD

**Issue by tgezginis** [calismamasam/calismamasam.com#20]

**Comment by puskuruk** [comment]
Issue'larda gördükten sonra araştırdım fakat okuduğum makalelerde hep kötü bahsedilmiş. Bu nedenle sizin neden AMP geliştirmesi düşündüğünüzü merak ettim. 

Örneğin => https://medium.com/@uistephen/why-not-google-amp-cf1aeb974463,
https://medium.com/@danbuben/why-amp-is-bad-for-your-site-and-for-the-web-e4d060a4ff31

**Comment by tgezginis** [comment]
@puskuruk açıkçası içerikleri Google'dan gelen ziyaretçilere daha hızlı bir deneyim sunmak için böyle bir issue açmıştım. Fakat sonrasında çok gerekli görmediğim için ekstra bir adım atmadım. Paylaştığın yazılardaki bazı maddelere katılmamak elde değil.

**Comment by puskuruk** [comment]
Cevabınız için teşekkür ederim @tgezginis  :+1:
