### ISSUE TITLE
Sosyal medyası hesapları ile giriş

### ISSUE THREAD

**Issue by enderahmetyurt** [calismamasam/calismamasam.com#3]
Merhaba @tgezginis facebook, twitter, github ile giriş olsa güzel olmaz mı :)

**Comment by tgezginis** [comment]
Bu konu üzerinde çalışıyorum, kısa bir süre içerisinde yayına alacağım. :)

**Comment by tgezginis** [comment]
Geliştirmeyi yayına aldım. Facebook, Twitter ve Github hesapları ile giriş yapılabilir durumda. 😎

https://github.com/calismamasam/calismamasam.com/pull/4
