### ISSUE TITLE
Var olan email ile sosyal hesaplarla girilemiyor

### ISSUE THREAD

**Issue by enderahmetyurt** [calismamasam/calismamasam.com#5]
Önceden kayıt olduğum email adresim ile Github hesabımın email adresi aynı olduğu için Github ile bağlanamıyorum. Bence user profile page olsaydı oradan social hesaplar eklenebilirdi. Ya da girerken aynı email ile varsa direk bağlanabilir ama bu durum email onayı olmadığı için pek iyi değil gibi duruyor.

**Comment by tgezginis** [comment]
Öncelikle e-mail onayını aktif hale getirip sonrasında da birleştirme ile ilgili geliştirmeler yapmak lazım.

**Comment by tgezginis** [comment]
https://github.com/calismamasam/calismamasam.com/pull/9 PR ile birlikte mevcut üyeler profile sayfalarından sosyal medya hesaplarını bağlayabilirler.

**Comment by enderahmetyurt** [comment]
Olmuş eline saglık.
